name: build

on:
  push:
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [debug, relwithdebinfo]
    steps:
    - uses: actions/checkout@v2
    - name: Apt dependencies
      run: sudo apt install clang
    - name: Python dependencies
      run: pip install --user cmake
    - name: configure
      run: |
           cmake --preset linux-ninja-clang
    - name: build
      run: |
           cmake --build --preset linux-ninja-clang-${{matrix.target}}
  