name: Code coverage check

on:
  push:

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [debug, relwithdebinfo]
    steps:
    - uses: actions/checkout@v2
    - name: Python dependencies
      run: pip install --user cmake coverage
    - name: build
      run: |
           cmake --workflow --preset linux-ninja-gnu-coverage-${{matrix.target}}
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}